kind: List
apiVersion: v1
items:

- kind: ImageStream
  apiVersion: v1
  metadata:
    labels:
      app: rhel7-weblogic
    name: rhel7-weblogic
  spec: {}

- kind: BuildConfig
  apiVersion: v1
  metadata:
    labels:
      app: rhel7-weblogic
    name: rhel7-weblogic
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: rhel7-weblogic:latest
    source:
      type: Git
      git:
        uri: https://github.com/mikeintoch/weblogic-openshift.git
      contextDir: rhel7-weblogic
    strategy:
      dockerStrategy:
        env:
        - name: FMW_BASEURL
          value: http://192.168.42.1/
        - name: FMW_VERSION
          value: 12.2.1.3.0
        from:
          kind: ImageStreamTag
          name: rhel7-java-180-oracle:latest
      type: Docker
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
