podTemplate(
    inheritFrom: "maven", 
    label: "myJenkins", 
    cloud: "openshift", 
    volumes: [
        persistentVolumeClaim(claimName: "m2repo", mountPath: "/home/jenkins/.m2/")
    ]) {

    node("myJenkins") {

        @Library('github.com/mikeintoch/jenkins-library@master')
        
        stage ('SCM checkout'){
            echo 'Checking out git repository'
            checkout scm
        }
    
        stage ('DEV - Image build'){
            echo 'Building docker image and deploying to Dev'
            buildApp('atmmovil-dev', "atmmovil")
            echo "This is the build number: ${env.BUILD_NUMBER}"
        }
    
        stage ('QA - Promote image'){
            echo 'Deploying to QA'
            promoteImage('atmmovil-dev', 'atmmovil-qa', 'atmmovil', 'latest')
        }
    
        stage ('Wait for approval'){
            input 'Approve to production?'
        }
    
        stage ('PRD - Promote image'){
            echo 'Deploying to production'
            promoteImage('atommovil-qa', 'atmmovil', 'atmmovil', env.BUILD_NUMBER)
        }

        stage ('PRD - Canary Deploy'){
            echo 'Performing a canary deployment'
            canaryDeploy('atmmovil', 'atmmovil', env.BUILD_NUMBER)
        }

    }
}
