kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "atmmovil-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/mikeintoch/weblogic-openshift"
      ref: "master"
  contextDir: "rhel7-weblogic-sampleapp"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: "Jenkinsfile"
