kind: BuildConfig
metadata:
  name: atmmovil-pipeline
spec:
  source:
    contextDir: rhel7-weblogic-sampleapp
    git:
      ref: master
      uri: 'https://github.com/mikeintoch/weblogic-openshift'
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline
